/*
Polaris Server

一个支持多语言、多框架的云原生服务发现和治理中心  提供高性能SDK和无侵入Sidecar两种接入方式  

API version: v0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package polaris

import (
	"encoding/json"
)

// V1AmountAdjuster struct for V1AmountAdjuster
type V1AmountAdjuster struct {
	Climb *V1ClimbConfig `json:"climb,omitempty"`
}

// NewV1AmountAdjuster instantiates a new V1AmountAdjuster object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1AmountAdjuster() *V1AmountAdjuster {
	this := V1AmountAdjuster{}
	return &this
}

// NewV1AmountAdjusterWithDefaults instantiates a new V1AmountAdjuster object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1AmountAdjusterWithDefaults() *V1AmountAdjuster {
	this := V1AmountAdjuster{}
	return &this
}

// GetClimb returns the Climb field value if set, zero value otherwise.
func (o *V1AmountAdjuster) GetClimb() V1ClimbConfig {
	if o == nil || o.Climb == nil {
		var ret V1ClimbConfig
		return ret
	}
	return *o.Climb
}

// GetClimbOk returns a tuple with the Climb field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1AmountAdjuster) GetClimbOk() (*V1ClimbConfig, bool) {
	if o == nil || o.Climb == nil {
		return nil, false
	}
	return o.Climb, true
}

// HasClimb returns a boolean if a field has been set.
func (o *V1AmountAdjuster) HasClimb() bool {
	if o != nil && o.Climb != nil {
		return true
	}

	return false
}

// SetClimb gets a reference to the given V1ClimbConfig and assigns it to the Climb field.
func (o *V1AmountAdjuster) SetClimb(v V1ClimbConfig) {
	o.Climb = &v
}

func (o V1AmountAdjuster) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Climb != nil {
		toSerialize["climb"] = o.Climb
	}
	return json.Marshal(toSerialize)
}

type NullableV1AmountAdjuster struct {
	value *V1AmountAdjuster
	isSet bool
}

func (v NullableV1AmountAdjuster) Get() *V1AmountAdjuster {
	return v.value
}

func (v *NullableV1AmountAdjuster) Set(val *V1AmountAdjuster) {
	v.value = val
	v.isSet = true
}

func (v NullableV1AmountAdjuster) IsSet() bool {
	return v.isSet
}

func (v *NullableV1AmountAdjuster) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1AmountAdjuster(val *V1AmountAdjuster) *NullableV1AmountAdjuster {
	return &NullableV1AmountAdjuster{value: val, isSet: true}
}

func (v NullableV1AmountAdjuster) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1AmountAdjuster) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


