/*
Polaris Server

一个支持多语言、多框架的云原生服务发现和治理中心  提供高性能SDK和无侵入Sidecar两种接入方式  

API version: v0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package polaris

import (
	"encoding/json"
)

// V1MatchString struct for V1MatchString
type V1MatchString struct {
	Type *int32 `json:"type,omitempty"`
	Value *string `json:"value,omitempty"`
	ValueType *int32 `json:"value_type,omitempty"`
}

// NewV1MatchString instantiates a new V1MatchString object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1MatchString() *V1MatchString {
	this := V1MatchString{}
	return &this
}

// NewV1MatchStringWithDefaults instantiates a new V1MatchString object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1MatchStringWithDefaults() *V1MatchString {
	this := V1MatchString{}
	return &this
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *V1MatchString) GetType() int32 {
	if o == nil || o.Type == nil {
		var ret int32
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1MatchString) GetTypeOk() (*int32, bool) {
	if o == nil || o.Type == nil {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *V1MatchString) HasType() bool {
	if o != nil && o.Type != nil {
		return true
	}

	return false
}

// SetType gets a reference to the given int32 and assigns it to the Type field.
func (o *V1MatchString) SetType(v int32) {
	o.Type = &v
}

// GetValue returns the Value field value if set, zero value otherwise.
func (o *V1MatchString) GetValue() string {
	if o == nil || o.Value == nil {
		var ret string
		return ret
	}
	return *o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1MatchString) GetValueOk() (*string, bool) {
	if o == nil || o.Value == nil {
		return nil, false
	}
	return o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *V1MatchString) HasValue() bool {
	if o != nil && o.Value != nil {
		return true
	}

	return false
}

// SetValue gets a reference to the given string and assigns it to the Value field.
func (o *V1MatchString) SetValue(v string) {
	o.Value = &v
}

// GetValueType returns the ValueType field value if set, zero value otherwise.
func (o *V1MatchString) GetValueType() int32 {
	if o == nil || o.ValueType == nil {
		var ret int32
		return ret
	}
	return *o.ValueType
}

// GetValueTypeOk returns a tuple with the ValueType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1MatchString) GetValueTypeOk() (*int32, bool) {
	if o == nil || o.ValueType == nil {
		return nil, false
	}
	return o.ValueType, true
}

// HasValueType returns a boolean if a field has been set.
func (o *V1MatchString) HasValueType() bool {
	if o != nil && o.ValueType != nil {
		return true
	}

	return false
}

// SetValueType gets a reference to the given int32 and assigns it to the ValueType field.
func (o *V1MatchString) SetValueType(v int32) {
	o.ValueType = &v
}

func (o V1MatchString) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Type != nil {
		toSerialize["type"] = o.Type
	}
	if o.Value != nil {
		toSerialize["value"] = o.Value
	}
	if o.ValueType != nil {
		toSerialize["value_type"] = o.ValueType
	}
	return json.Marshal(toSerialize)
}

type NullableV1MatchString struct {
	value *V1MatchString
	isSet bool
}

func (v NullableV1MatchString) Get() *V1MatchString {
	return v.value
}

func (v *NullableV1MatchString) Set(val *V1MatchString) {
	v.value = val
	v.isSet = true
}

func (v NullableV1MatchString) IsSet() bool {
	return v.isSet
}

func (v *NullableV1MatchString) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1MatchString(val *V1MatchString) *NullableV1MatchString {
	return &NullableV1MatchString{value: val, isSet: true}
}

func (v NullableV1MatchString) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1MatchString) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


